# Generated by Django 5.0.6 on 2024-09-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incidentreport",
            name="occurrence_time",
            field=models.DateTimeField(auto_created=True),
        ),
    ]
